# Numerical Python End to End in Detail
Numpy:
Numpy- is a Numerical Python

It is developed by Travis Oliphant in 2005

Numpy has functions to work on linear algebra, fourier transform, and matrices

Its basically used to work with array, It can work with multidimentional Arrays

* NumPy (short for Numerical Python) is a Python library that provides support for large, multi-dimensional arrays and matrices, as well as a large collection of mathematical functions to operate on these arrays. NumPy is a fundamental package for scientific computing with Python, as it forms the basis for many other data science and machine learning libraries.

In [1]:
import numpy as np
print("Current numpy version is:-",np.__version__)

Current numpy version is:- 1.24.2


In [2]:
x = np.array([1,2,3,4,5,6])

print(x)
print(type(x),'\n')

a = [1,2,3,4,5,6]

x = np.array(a)
print(x)
print(type(x))

[1 2 3 4 5 6]
<class 'numpy.ndarray'> 

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
x = np.array([1,2,3])

print(x)
print("No. of dimensions:",x.ndim)

[1 2 3]
No. of dimensions: 1


In [4]:
x = np.array(1)

print(x)
print("No. of dimensions:",x.ndim)

1
No. of dimensions: 0


In [5]:
a = [[1],[2]]

b = np.array(a)
print(b)
print("Dimensions:",b.ndim)

[[1]
 [2]]
Dimensions: 2


In [76]:
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(x)
print("Dimensions:",x.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3


In [7]:
# accesing the elements
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(x)

# 1st way
print(x[0][1])

#2nd way
print(x[1,1])

# dimensions 
print("Dimensions:",x.ndim)

[[1 2 3]
 [4 5 6]]
2
5
Dimensions: 2


In [89]:
x = [[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]]

arr = np.array(x)
# print(arr,'\n')

print(arr[0][0][2])
print(arr[1,1,1])

3
50


In [90]:
x = [[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]]

arr = np.array(x)
# print(arr)

print("Dimensions:",arr.ndim)

print(arr[1,1,1])

Dimensions: 3
50


In [91]:
a = [[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]],[[100,200,300],[400,500,600]],[[11,22,33],[44,55,66]]]
arr = np.array(a)

# print(arr)
print("Dimensions:",arr.ndim)

print(arr[0],'\n')
print(arr[1],'\n')
print(arr[2],'\n')
print(arr[3])

Dimensions: 3
[[1 2 3]
 [4 5 6]] 

[[10 20 30]
 [40 50 60]] 

[[100 200 300]
 [400 500 600]] 

[[11 22 33]
 [44 55 66]]


## Array Slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [11]:
# indexing array
import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9,10])

print(len(x))
print(x[0:])
print(x[0:5])
print(x[5:])

10
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]
[ 6  7  8  9 10]


In [12]:
# negative indexing
x = np.array([1,2,3,4,5,6,7,8,9,10])

z = x[::-1]
print(x[-9:-3])

print(z)
a = np.sort(z)
print(a)

[2 3 4 5 6 7]
[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# step
x = np.array([1,2,3,4,5,6,7,8,9,10])

print(x[0:10:2])
print(x[0:10:3])
print(x[0:10:4])
print(x[0:10:5])

[1 3 5 7 9]
[ 1  4  7 10]
[1 5 9]
[1 6]


## Slicing of 2D array

In [14]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0])
print(arr[1])
print("Dimensions:",arr.ndim)

[1 2 3 4 5]
[ 6  7  8  9 10]
Dimensions: 2


In [15]:
import numpy as np

ar = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(ar[0])
print(ar[1],'\n')

print(ar[0:2, 0:4])

[1 2 3 4 5]
[ 6  7  8  9 10] 

[[1 2 3 4]
 [6 7 8 9]]


In [16]:
ar = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])

print(ar.size)
print(ar.shape)

print(ar[0:3, 0:3])

12
(3, 4)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Data types

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

1. i - integer
2. b - boolean
3. u - unsigned integer
4. f - float
5. c - complex float
6. m - timedelta
7. M - datetime
8. O - object
9. S - string
10. U - unicode string
11. V - fixed chunk of memory for other type ( void )

In [17]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9], dtype = int)

print(x)
x.dtype

[1 2 3 4 5 6 7 8 9]


dtype('int32')

## Data type conversion (typecasting)

In [18]:
# float to int
import numpy as np

ar = np.array([1.2, 2.3, 3.4, 4.5, 5.6, 6.7, 7.8, 8.9])

arr = ar.astype('i')

print(ar)
print(arr)

print(ar.dtype)
print(arr.dtype)

[1.2 2.3 3.4 4.5 5.6 6.7 7.8 8.9]
[1 2 3 4 5 6 7 8]
float64
int32


In [19]:
# int to bool

ar = np.array([12,0,56,0])

arr = ar.astype(bool)

print(ar)
print(arr)

print(ar.dtype)
print(arr.dtype)

[12  0 56  0]
[ True False  True False]
int32
bool


## Copy and View

In [20]:
# copy
import numpy as np

ar = np.array([1,2,3,4,5])
x = ar.copy()
print(x)
x[2] = 10
print(x)
print(ar)

[1 2 3 4 5]
[ 1  2 10  4  5]
[1 2 3 4 5]


In [21]:
# view

ar = np.array([1,2,3,4,5])
x = ar.view()
print(x)
x[2] = 10
print(x)
print(ar)

[1 2 3 4 5]
[ 1  2 10  4  5]
[ 1  2 10  4  5]


## Array Reshaping

In [22]:
import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

z = x.reshape(3,4)

print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
    
x = a.reshape(2,2,5)
print(x)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


## Unknown Dimension

In [24]:
import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

b = x.reshape(2,-1,5)
a = x.reshape(2,-1,2)
z = x.reshape(5,-1,2)
c = x.reshape(10,-1)

print('Array B-')
print(b,'\n')

print('Array A-')
print(a,'\n')

print('Array Z-')
print(z,'\n')

print('Array C-')
print(c)

Array B-
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]] 

Array A-
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]] 

Array Z-
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]] 

Array C-
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


## Flattening arrays

In [25]:
# one way
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar,'\n')

arr = ar.flatten()
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9]


In [26]:
# another way
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar,'\n')

arr = ar.reshape(-1)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9]


## Numpy Array Iterating

In [27]:
# on 1D array
a = np.array([1,2,3,4,5])

for i in a:
    print(i)

1
2
3
4
5


In [28]:
# on 2D array
x = np.array([[1,2,3],[4,5,6]])

for i in x:
    print(i,'\n')
    for y in i:
        print(y,'\n')

[1 2 3] 

1 

2 

3 

[4 5 6] 

4 

5 

6 



In [29]:
# on 3D array
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in a:
    print(x,'\n')
    for y in x:
        print(y,'\n')
        for z in y:
            print(z,'\n')

[[1 2 3]
 [4 5 6]] 

[1 2 3] 

1 

2 

3 

[4 5 6] 

4 

5 

6 

[[ 7  8  9]
 [10 11 12]] 

[7 8 9] 

7 

8 

9 

[10 11 12] 

10 

11 

12 



## iterating arrays using nditer() 

In [30]:
# iterating over 3D arrays 
import numpy as np

x = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

for i in np.nditer(x):
    print(i)

1
2
3
4
5
6
7
8
9


In [31]:
ar = np.array([1,2,3,4,5])

for i in np.nditer(ar, flags = ['buffered'], op_dtypes = ['S']):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'


In [32]:
ar = np.array([1,2,3,4,5])

for i in np.nditer(ar, flags = ['buffered'], op_dtypes = ['float']):
    print(i)

1.0
2.0
3.0
4.0
5.0


In [33]:
# slicing of a numpy array and steps in iteration

ar = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

for i in np.nditer(ar[0:4,0:5:2]):
    print(i)

1
3
5
6
8
10
11
13
15
16
18
20


## Iteration using ndenumerate()

In [34]:
# on 1D array
x = np.array([1,2,3,4,5,6,7,8,9])

for a, b in np.ndenumerate(x):
    print(f"Location:- {a} - Value:- {b}")

Location:- (0,) - Value:- 1
Location:- (1,) - Value:- 2
Location:- (2,) - Value:- 3
Location:- (3,) - Value:- 4
Location:- (4,) - Value:- 5
Location:- (5,) - Value:- 6
Location:- (6,) - Value:- 7
Location:- (7,) - Value:- 8
Location:- (8,) - Value:- 9


In [35]:
# on 2D array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

for x, z in np.ndenumerate(a):
    print(f"Location:- {x} - Value:- {z}")

Location:- (0, 0) - Value:- 1
Location:- (0, 1) - Value:- 2
Location:- (0, 2) - Value:- 3
Location:- (1, 0) - Value:- 4
Location:- (1, 1) - Value:- 5
Location:- (1, 2) - Value:- 6
Location:- (2, 0) - Value:- 7
Location:- (2, 1) - Value:- 8
Location:- (2, 2) - Value:- 9


In [36]:
# on 3D array
z = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x, y in np.ndenumerate(z):
    print(f"Location:- {x} - Value:- {y}")

Location:- (0, 0, 0) - Value:- 1
Location:- (0, 0, 1) - Value:- 2
Location:- (0, 0, 2) - Value:- 3
Location:- (0, 1, 0) - Value:- 4
Location:- (0, 1, 1) - Value:- 5
Location:- (0, 1, 2) - Value:- 6
Location:- (1, 0, 0) - Value:- 7
Location:- (1, 0, 1) - Value:- 8
Location:- (1, 0, 2) - Value:- 9
Location:- (1, 1, 0) - Value:- 10
Location:- (1, 1, 1) - Value:- 11
Location:- (1, 1, 2) - Value:- 12


## Joining array

concatenate() = Merge numpy arrays

In [37]:
# on 1D array

a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

x = np.concatenate((a1,a2))
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [38]:
# on 2D array
# using axis option

x1 = np.array([[1,2,3],[4,5,6]])
x2 = np.array([[7,8,9],[10,11,12]])

a = np.concatenate((x1,x2), axis = 0)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
# on 2D array
# using axis option

x1 = np.array([[1,2,3],[4,5,6]])
x2 = np.array([[7,8,9],[10,11,12]])

a = np.concatenate((x1,x2), axis = 1)
print(a)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Joining arrays using stack function

In [40]:
ar1 = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])

x = np.stack((ar1,ar2),axis=0)
print(x,'\n')

y = np.stack((ar1,ar2),axis=1)
print(y)

[[1 2 3 4]
 [5 6 7 8]] 

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [41]:
# hstack() = horizontal stack
ar1 = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])

x = np.hstack((ar1,ar2))
print(x)

[1 2 3 4 5 6 7 8]


In [42]:
# vstack = verticle stack
ar1 = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])

x = np.vstack((ar1,ar2))
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [43]:
ar1 = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])

x = np.dstack((ar1,ar2))
print(x)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


## Splitting array

joining merges multiple arrays into one and splitting breaks one array into multiple arrays

In [44]:
# one way
import numpy as np

ar = np.array([1,2,3,4,5,6,7,8,9,10])

x = np.array_split(ar,1)
y = np.array_split(ar,2)
z = np.array_split(ar,5)
a = np.array_split(ar,10)

print(x,'\n')
print(y,'\n')
print(z,'\n')
print(a)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])] 

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])] 

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])] 

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9]), array([10])]


In [45]:
# 
ar = np.array([1,2,3,4,5,6,7,8,9,10])

x = np.split(ar,5)
print(x)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


## hsplit(), vsplit() & dsplit()

In [46]:
# hsplit()
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])

b = np.hsplit(a,4)
print(b)

[array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([[4],
       [8]])]


In [47]:
# vsplit()
a = np.array([[1,2,3,4],[5,6,7,8]])

b = np.vsplit(a,2)
print(b)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [48]:
# dsplit()
a = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]])

b = np.dsplit(a,2)
print(b)

[array([[[ 1,  2],
        [ 5,  6]],

       [[10, 20],
        [50, 60]]]), array([[[ 3,  4],
        [ 7,  8]],

       [[30, 40],
        [70, 80]]])]


## Arithmetic operation on array

In [49]:
x =np.array([[1,2,3,4],[5,6,7,8]])

print("Addition:\n",x + 1,'\n')
print("Subtraction:\n",x - 2,'\n')
print("Multiplication:\n",x * 5,'\n')
print("Division:\n",x / 2)

Addition:
 [[2 3 4 5]
 [6 7 8 9]] 

Subtraction:
 [[-1  0  1  2]
 [ 3  4  5  6]] 

Multiplication:
 [[ 5 10 15 20]
 [25 30 35 40]] 

Division:
 [[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]]


## Searching arrays

where() method is used for searching in array

In [50]:
# finding elements in 1D array
ar = np.array([1,2,3,4,5,6,6,7,8,6,9,6,4,2,3,4,1,6,8,9])

x = np.where(ar == 4)
y = np.where(ar == 6)
z = np.where(ar == 2)

print("Location:",x,'\n')
print("Location:",y,'\n')
print("Location:",z)

Location: (array([ 3, 12, 15], dtype=int64),) 

Location: (array([ 5,  6,  9, 11, 17], dtype=int64),) 

Location: (array([ 1, 13], dtype=int64),)


In [51]:
ar = np.array([1,2,3,4,5,6,6,7,8,6,9,6,4,2,3,4,1,6,8,9])

x = np.where(ar%2 == 0)

print("Location of Even numbers:",x)

Location of Even numbers: (array([ 1,  3,  5,  6,  8,  9, 11, 12, 13, 15, 17, 18], dtype=int64),)


## Search sorted

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [52]:
ar = np.array([1,3,4,5,6,8,9])

x = np.searchsorted(ar, 2)
y = np.searchsorted(ar, 7)

print(x)
print(y)

1
5


In [53]:
arr = np.array([1,2,3,4,5,6])

x = np.searchsorted(arr, 2.5, side = 'right')
print(x)

2


In [54]:
arr = np.array([1,2,3,4,5,6])

x = np.searchsorted(arr, 3.3, side = 'left')
print(x)

3


In [55]:
# multiple values
x = np.array([10,30,40,70,90])

z = np.searchsorted(x, [20, 50, 60, 80])
print(z)

[1 3 3 4]


## Sorting arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [56]:
# sort() on array
arr = np.array([30, 20, 40, 10])

print(np.sort(arr))

[10 20 30 40]


In [57]:
# sort() on string
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [58]:
# sort on boolean
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [59]:
# sort on 2D array
arr = np.array([[1,3, 2, 4], [5, 8, 7, 6]])

print(np.sort(arr))

[[1 2 3 4]
 [5 6 7 8]]


## Filtering Arrays


Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [60]:
import numpy as np

x = np.array([1,2,3,4,5])
y = [True, False, True, False, True]

print(x[y])

[1 3 5]


In [61]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr,'\n')

x = []

for i in arr:
    if i >= 7 or i <= 3:
        x.append(True)
    else:
        x.append(False)

print(x)

print(arr[x])

[1 2 3 4 5 6 7 8 9] 

[True, True, True, False, False, False, True, True, True]
[1 2 3 7 8 9]


In [62]:
arr = np.arange(1,21)

bool_val = []

for i in arr:
    if i <= 5 or i >= 15:
        bool_val.append(True)
    else:
        bool_val.append(False)
        
print(arr,'\n')
print(bool_val,'\n')
print(arr[bool_val])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

[True, True, True, True, True, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True] 

[ 1  2  3  4  5 15 16 17 18 19 20]


In [63]:
arr = np.arange(1,21)

bool_val = []

for i in arr:
    if i % 2 == 0:
        bool_val.append(True)
    else:
        bool_val.append(False)
        
print(arr,'\n')
print(bool_val,'\n')
print(arr[bool_val])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

[False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True] 

[ 2  4  6  8 10 12 14 16 18 20]


## Other Numpy Functions

In [64]:
# arange()
arr = np.arange(25)
# arr = np.array([1,3,2,4,6,5,7,8,10,9])
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [65]:
arr_2D = np.reshape(arr,(5,5))

print(arr_2D)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [66]:
arr_2D.min()

0

In [67]:
arr_2D.max()

24

In [68]:
arr_2D.argsort()

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [69]:
arr_2D.diagonal()

array([ 0,  6, 12, 18, 24])

In [70]:
arr_2D.sum()

300

In [71]:
arr_2D.mean()

12.0

In [72]:
arr_2D.nonzero()

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4,
        4, 4], dtype=int64),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2,
        3, 4], dtype=int64))

In [73]:
print(arr_2D.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [74]:
arr = np.linspace(1,20,5)

print(arr)

[ 1.    5.75 10.5  15.25 20.  ]


In [75]:
x = np.random.randn(10)
print(x)

[ 0.15446113  0.91075805  1.03433858 -1.87052156 -0.91171325  0.8885958
 -0.22893594  0.43179573  0.95206486 -0.36949107]
